version: '2.1'

services:    
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        volumes:
            - .:/usr/src/app/
        restart: unless-stopped
        env_file: .env
        ports:
            - "8080:8080"
        depends_on:
            - db