version: '2.1'

services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        volumes:
        - ./init.sql:/data/application/init.sql
        env_file:
            - .env
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: secret
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        volumes:
            - .:/usr/src/app/
        restart: unless-stopped
        env_file: .env
        ports:
            - "8080:8080"
        depends_on:
            - db